CREATE DATABASE QLDKMH
GO
USE QLDKMH
GO

SET DATEFORMAT DMY

-- CREATE TABLES

-- CREATE TABLE SINHVIEN
CREATE TABLE SINHVIEN 
(
	MaSV CHAR(8) PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	NgaySinh SMALLDATETIME NOT NULL,
	GioiTinh NVARCHAR(3),
	MaNganh CHAR(4) NOT NULL,
	MaDoiTuong CHAR(4) NOT NULL,
	MaHuyen CHAR(4) NOT NULL,
)

-- CREATE TABLE DOITUONG
CREATE TABLE DOITUONG
(
	MaDoiTuong CHAR(4) PRIMARY KEY,
	TenDoiTuong NVARCHAR(40),
	TiLeGiamHP INT
)

-- CREATE TABLE TINH
CREATE TABLE TINH
(	
	MaTinh CHAR(4) PRIMARY KEY,
	TenTinh NVARCHAR(30)
)

-- CREATE TABLE HUYEN
CREATE TABLE HUYEN
(
	MaHuyen CHAR(4) PRIMARY KEY,
	TenHuyen NVARCHAR(30),
	MaTinh CHAR(4) NOT NULL,
	UuTien BIT,
)

-- CREATE TABLE KHOA
CREATE TABLE KHOA
(
	MaKhoa CHAR(4) PRIMARY KEY,
	TenKhoa NVARCHAR(40)
)

-- CREATE TABLE NGANH
CREATE TABLE NGANH 
(
	MaNganh CHAR(4) PRIMARY KEY,
	TenNganh NVARCHAR(40),
	MaKhoa CHAR(4)
)

-- CREATE CHECK CONSTRAINTS
ALTER TABLE SINHVIEN ADD CONSTRAINT CHECK_GIOITINH CHECK (GioiTinh IN (N'Nam', N'Nữ'))
ALTER TABLE DOITUONG ADD CONSTRAINT CHECK_TILE CHECK (TiLeGiamHP >= 0)



-- CREATE FOREIGN KEY CONSTRAINTS
ALTER TABLE HUYEN ADD CONSTRAINT FK_HUYEN_TINH FOREIGN KEY (MaTinh) REFERENCES TINH(MaTinh)	 
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_HUYEN FOREIGN KEY (MaHuyen) REFERENCES HUYEN(MaHuyen)
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_NGANH FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_DOITUONG FOREIGN KEY (MaDoiTuong) REFERENCES DOITUONG(MaDoiTuong)
ALTER TABLE NGANH ADD CONSTRAINT FK_NGANH_KHOA FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)


